#!/usr/bin/env python3
"""BASTION-01 v2 ("Pacific Rim x Tokyo" design) - hard-surface build for Blender, from scratch and non-interactive.

    python art/mech_v2/build_bastion_v2.py [--no-render] [--no-uv] [--no-textures] [--quick] [--only=front,side,...]
    blender -b -P art/mech_v2/build_bastion_v2.py -- [flags]

Stages: build parts + variants -> rig + rigid binding -> per-material UV atlases -> contract checks (raise on violation) -> pose tests ->
FBX/GLB/JSON (+ variants file) -> Cycles bake of AO/thickness/normal/position/id -> PBR textures (player + enemy) -> preview renders.
`--quick` bakes at 1024 and renders fewer samples (for iteration)."""
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
OUT = os.path.join(HERE, "out")
WORK = os.path.join(HERE, "work")          # bake cache (git-ignored)
TEX = os.path.join(OUT, "textures")        # full-size PBR sets (git-ignored, regenerated by this script)

from build_params import PARAMS  # noqa: E402

RENDER = dict(res=(1600, 1000), samples=96)
CLASH_TOLERANCE_M = 0.8
TEX_RES = 2048


def main(argv):
    flags = set(argv)
    quick = "--quick" in flags
    import bpy  # noqa: F401
    from lib import hs, design, rig, uv, checks, pose, export, variants, z_all
    t0 = time.time()
    for d in (OUT, WORK):
        os.makedirs(d, exist_ok=True)

    hs.reset()
    z_all.build_all(PARAMS)
    variants.build_all(PARAMS)
    arm = rig.build_armature(design.skeleton(PARAMS))
    rig.bind_all(arm)
    rig.bind_variants(arm)
    print("[1/8] built %d parts + %d variants (%d tris in the contract mesh)" % (len(hs.REG.parts), len(hs.REG.variants), checks_tris(hs, checks)))

    use_uv = "--no-uv" not in flags
    same, other = variants.finalize_dents()
    print("      dent variants sharing the original's UVs: %d, packed separately: %d" % (len(same), len(other)))
    if use_uv:
        packable = list(hs.REG.parts) + [o for o in hs.REG.variants if o.get("dent_of") is None]
        target, dens = uv.unwrap_all(parts=packable)
        variants.copy_uvs_from_originals()
        print("[2/8] UV atlases packed (one per material), uniform texel density %.5f UV/m = %.1f px/m at 2048" % (target, target * 2048))
    variants.build_detached_arms(PARAMS)
    stats = checks.run(PARAMS, check_uv=use_uv)
    print("[3/8] contract checks passed")

    errs = pose.check_limits()
    pose_results = {}
    for name in pose.POSES:
        pose.reset_pose(arm)
        pose.apply_pose(arm, name)
        worst = pose.clash_report(arm, tol=CLASH_TOLERANCE_M)
        pose_results[name] = {"angles_deg": pose.POSES[name], "clashes_over_tolerance": [{"depth_m": round(dd, 3), "a": a, "b": b} for dd, a, b in worst]}
        for dd, a, b in worst:
            errs.append("pose %s: %s penetrates %s by %.2f m" % (name, a, b, dd))
    pose.reset_pose(arm)
    if errs:
        raise SystemExit("pose tests failed:\n" + "\n".join(errs))
    print("[4/8] pose tests passed (%s)" % ", ".join(pose.POSES))

    export.write_json(os.path.join(OUT, "BASTION_01_v2_parts.json"), export.parts_report(PARAMS, stats))
    export.write_json(os.path.join(OUT, "BASTION_01_v2_pose_tests.json"), {
        "convention": "rotations in degrees about WORLD axes through the joint, relative to the parent's pose; X pitch (negative = forward/up), Y roll, Z yaw/side swing",
        "clash_tolerance_m": CLASH_TOLERANCE_M,
        "joint_limits_deg": {b: {a: list(r) for a, r in lim.items()} for b, lim in pose.LIMITS.items()}, "poses": pose_results})
    export.export_fbx(os.path.join(OUT, "BASTION_01_v2.fbx"))
    export.export_glb(os.path.join(OUT, "BASTION_01_v2.glb"))
    export.export_variants(os.path.join(OUT, "BASTION_01_v2_variants.fbx"))
    big = export.package_large(OUT, ("BASTION_01_v2.fbx", "BASTION_01_v2.glb", "BASTION_01_v2_variants.fbx"))
    print("[5/8] exported FBX, GLB, variants FBX, parts and pose JSON%s" % ("; zipped (>limit): " + ", ".join(big) if big else ""))

    if "--no-textures" not in flags:
        from lib import bakeall
        manifest = bakeall.run(WORK, TEX, 1024 if quick else TEX_RES, rebake="--rebake" in flags)
        export.write_json(os.path.join(OUT, "textures_manifest.json"), manifest)
        print("[6/8] baked maps + PBR textures (player and enemy sets): %d files" % sum(len(v) for s in manifest["sets"].values() for v in s.values()))

    only = None
    for f in flags:
        if f.startswith("--only="):
            only = set(f.split("=", 1)[1].split(","))
    if "--no-render" not in flags:
        from lib import previews
        previews.render_all(PARAMS, OUT, TEX, only, quick, arm)
        print("[7/8] previews rendered")
    n, h = export.verify_fbx(os.path.join(OUT, "BASTION_01_v2.fbx"), len(hs.REG.parts), PARAMS["height"])
    print("[8/8] FBX re-import check: %d meshes, height %.2f m, bones and orientation as in the contract" % (n, h))
    print("done in %.0f s" % (time.time() - t0))


def checks_tris(hs, checks):
    return sum(checks.tris(o) for o in hs.REG.parts)


if __name__ == "__main__":
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else sys.argv[1:]
    main(argv)
