#include "iv/HackExport.h"

#include <cstdarg>
#include <cstdio>

#include "iv/HackGame.h"

namespace iv {

namespace {

void Add(std::string* s, const char* fmt, ...) {
  char buf[512];
  va_list ap;
  va_start(ap, fmt);
  std::vsnprintf(buf, sizeof buf, fmt, ap);
  va_end(ap);
  *s += buf;
}

const char* StageName(HackStage k) { return k == HackStage::Path ? "path" : k == HackStage::Rhythm ? "rhythm" : "frequency"; }

}  // namespace

std::string HackDifficultyJson() {
  std::string s = "{\n  \"version\": 1,\n  \"note\": \"Mirror of tune::kHackLevels in core/include/iv/Tuning.h (a test keeps them equal)\",\n";
  Add(&s, "  \"constants\": {\"leadTicks\": %d, \"travelTicks\": %d, \"alarmHeat\": %d, \"tripHeat\": %d, \"tripHeatAfter\": %d, \"heatDecayPerTick\": %.3f, "
          "\"tripPenaltyMult\": %d, \"undoPenaltyTicks\": %d, \"lockSpeedGain\": %.3f, \"alarmSpeedMult\": %.3f, \"lockHalfMinDeg\": %.3f},\n",
      tune::kHackLeadTicks, tune::kHackTravelTicks, tune::kHackAlarmHeat, tune::kHackTripHeat, tune::kHackTripHeatAfter, static_cast<double>(tune::kHackHeatDecayPerTick),
      tune::kHackTripPenaltyMult, tune::kHackUndoPenaltyTicks, static_cast<double>(tune::kHackLockSpeedGain), static_cast<double>(tune::kHackAlarmSpeedMult),
      static_cast<double>(tune::kHackLockHalfMinDeg));
  s += "  \"levels\": [\n";
  for (int i = 0; i < 10; ++i) {
    const tune::HackLevel& L = tune::kHackLevels[i];
    Add(&s, "    {\"level\": %d, \"stages\": %d, \"gridW\": %d, \"gridH\": %d, \"blocks\": %d, \"ice\": %d, \"keys\": %d, \"lanes\": %d, \"impulses\": %d, "
            "\"gapMin\": %d, \"gapMax\": %d, \"hitWindow\": %d, \"locks\": %d, \"lockHalfDeg\": %.3f, \"lockShrink\": %.3f, \"relSpeed\": %.3f, "
            "\"timeLimitSec\": %d, \"penaltyMs\": %d, \"heatPerMistake\": %d}%s\n",
        L.level, L.stages, L.gridW, L.gridH, L.blocks, L.ice, L.keys, L.lanes, L.impulses, L.gapMin, L.gapMax, L.hitWindow, L.locks, static_cast<double>(L.lockHalfDeg),
        static_cast<double>(L.lockShrink), static_cast<double>(L.relSpeed), L.timeLimitSec, L.penaltyMs, L.heatPerMistake, i < 9 ? "," : "");
  }
  s += "  ]\n}\n";
  return s;
}

std::string HackLevelsJson(int perLevel) {
  std::string s = "{\n  \"version\": 1,\n  \"note\": \"Generated by core/tools/hack_export.cpp from HackGame::Generate*; seed = level * 1000 + index; "
                  "stage seed = HackGame::StageSeed(seed, stageIndex, 0)\",\n  \"sessions\": [\n";
  for (int level = 1; level <= 10; ++level) {
    for (int i = 0; i < perLevel; ++i) {
      const uint64_t seed = static_cast<uint64_t>(level) * 1000u + static_cast<uint64_t>(i);
      const std::vector<HackStageSpec> stages = HackGame::StagesFor(level);
      Add(&s, "    {\"level\": %d, \"seed\": %llu, \"timeLimitTicks\": %d, \"stages\": [\n", level, static_cast<unsigned long long>(seed), HackGame::DefaultTimeLimit(level));
      for (size_t k = 0; k < stages.size(); ++k) {
        const uint64_t ss = HackGame::StageSeed(seed, static_cast<int>(k), 0);
        Add(&s, "      {\"kind\": \"%s\", \"boss\": %s, ", StageName(stages[k].kind), stages[k].boss ? "true" : "false");
        if (stages[k].kind == HackStage::Path) {
          const PathLayout p = HackGame::GeneratePath(level, ss);
          Add(&s, "\"w\": %d, \"h\": %d, \"entry\": [%d, %d], \"core\": [%d, %d], \"cells\": [", p.w, p.h, p.sx, p.sy, p.cx, p.cy);
          for (int y = 0; y < p.h; ++y) {
            s += y ? ", \"" : "\"";
            for (int x = 0; x < p.w; ++x) s += static_cast<char>('0' + p.cell[static_cast<size_t>(y * p.w + x)]);
            s += "\"";
          }
          s += "], \"keys\": [";
          for (size_t j = 0; j < p.keys.size(); ++j) Add(&s, "%s[%d, %d]", j ? ", " : "", p.keys[j] % p.w, p.keys[j] / p.w);
          s += "], \"solution\": \"";
          for (const HackStep& st : p.solution) s += st.dx > 0 ? 'R' : st.dx < 0 ? 'L' : st.dy > 0 ? 'D' : 'U';
          s += "\"}";
        } else if (stages[k].kind == HackStage::Rhythm) {
          const RhythmLayout r = HackGame::GenerateRhythm(level, ss, stages[k].boss);
          Add(&s, "\"lanes\": %d, \"impulses\": [", r.lanes);
          for (size_t j = 0; j < r.impulses.size(); ++j) Add(&s, "%s[%d, %d]", j ? ", " : "", r.impulses[j].tick, r.impulses[j].lane);
          s += "]}";
        } else {
          const FreqLayout f = HackGame::GenerateFreq(level, ss, stages[k].boss);
          Add(&s, "\"locks\": %d, \"hackerStart\": %.3f, \"iceStart\": %.3f, \"hackerSpeed\": %.4f, \"iceSpeed\": %.4f, \"halfDeg\": [", f.locks,
              static_cast<double>(f.hackerStart), static_cast<double>(f.iceStart), static_cast<double>(f.hackerSpeed), static_cast<double>(f.iceSpeed));
          for (size_t j = 0; j < f.halfDeg.size(); ++j) Add(&s, "%s%.3f", j ? ", " : "", static_cast<double>(f.halfDeg[j]));
          s += "]}";
        }
        s += k + 1 < stages.size() ? ",\n" : "\n";
      }
      s += "    ]}";
      s += (level == 10 && i == perLevel - 1) ? "\n" : ",\n";
    }
  }
  s += "  ]\n}\n";
  return s;
}

}  // namespace iv
